<a href="https://colab.research.google.com/github/padmasri2005/DataScience_Tasks/blob/main/NUMPY_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Part 1: Creating and Reshaping Arrays

**1)Create Arrays:**
- Create two NumPy arrays:

- A 1D array of 10 equally spaced values between 0 and 50.
- A 2D array of shape (3x3) containing random integers between 5 and 20.

In [2]:
a1 = np.linspace(0,50,10)
print(a1)
a2 = np.random.randint(5,20,9)
a2=a2.reshape(3,3)
print(a2)

[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]
[[19 11  8]
 [16  5  7]
 [16  5  5]]


**2) Array Dimensions:**
- Print the dimensions of both arrays.
- Print the shape of both arrays.

In [3]:
print("Dimensions of Arr1 : ",a1.ndim)
print("Dimensions of Arr2 : ",a2.ndim)
print("Shape of arr1 : ",a1.shape)
print("Shape of arr2 : ",a2.shape)



Dimensions of Arr1 :  1
Dimensions of Arr2 :  2
Shape of arr1 :  (10,)
Shape of arr2 :  (3, 3)


**3. Reshaping:**
- Reshape the 1D array into a 2D array with shape (2x5).
- Print the reshaped array.
- Flatten the reshaped array back to 1D and print it.

In [4]:
# 1d array to 2d
a1 = a1.reshape(2,5)
print("1d array to 2d")
print(a1)

#flatten array
a1 = a1.reshape(-1)
print("Flattening")
print(a1)

1d array to 2d
[[ 0.          5.55555556 11.11111111 16.66666667 22.22222222]
 [27.77777778 33.33333333 38.88888889 44.44444444 50.        ]]
Flattening
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]


# Part 2: Indexing and Slicing

**4. Indexing:**
- For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
- Extract the first two rows and the last two columns of the array.

In [5]:
print(a2)
print(a2[1,2])
print(a2[0],a2[1])
print(a2[0:2,1:])

[[19 11  8]
 [16  5  7]
 [16  5  5]]
7
[19 11  8] [16  5  7]
[[11  8]
 [ 5  7]]


**5. Slicing:**
- Slice the first four elements from the flattened 1D array.
- Reverse the elements of the 1D array using slicing.

In [6]:
print(a1[:4])
print(a1[::-1])

[ 0.          5.55555556 11.11111111 16.66666667]
[50.         44.44444444 38.88888889 33.33333333 27.77777778 22.22222222
 16.66666667 11.11111111  5.55555556  0.        ]


# Part 3: Array Operations
**6. Array Arithmetic**:

- Create another 1D array of 10 integers between 1 and 10.
- Perform the following element-wise operations between the 1D
arrays created in Part 1 and Part 3:

  - Addition

  - Multiplication

  - Subtract a constant value (e.g.,5) from the array.

In [7]:
arr1 = np.arange(1,11)
print(a1+arr1)
print(a1-arr1)
print(arr1 - 5)

[ 1.          7.55555556 14.11111111 20.66666667 27.22222222 33.77777778
 40.33333333 46.88888889 53.44444444 60.        ]
[-1.          3.55555556  8.11111111 12.66666667 17.22222222 21.77777778
 26.33333333 30.88888889 35.44444444 40.        ]
[-4 -3 -2 -1  0  1  2  3  4  5]


# Part 4: Random Number Generation and Copying

**7. Random Numbers:**
- Create a 1D array of 5 random values between 0 and 1.
- Create another 1D array of 5 random values between -1 and 1.
Part

In [8]:
r1 = np.random.rand(5)
print(r1)
r2 = np.random.randint(-1,1,5)
print(r2)

[0.45706399 0.24035388 0.16176068 0.40962319 0.1181093 ]
[-1 -1  0  0  0]


# Part 5: Bonus
**8. Challenge Task:**
- Write a program that asks the user to input a number (n), and then
generates an n x n array of random integers between 1 and 100.
- Find the sum of all the elements in the array and print the result.

In [10]:
n = int(input("Enter the value of n : "))
rand = np.random.randint(1,100,n*n)
array1 = rand.reshape(n,n)
print(array1)
print(sum(sum(array1)))

Enter the value of n : 3
[[83 13  8]
 [75 26 52]
 [38 25  9]]
329
